name: Build and push image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: git-sync

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        if: github.event_name == 'push'
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/193123067890/locations/global/workloadIdentityPools/ci-knada-images/providers/ci-knada-images
          service_account: ci-knada-images@knada-gcp.iam.gserviceaccount.com

      - uses: docker/login-action@v2
        if: github.event_name == 'push'
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/login-action@v3
        if: github.event_name == 'push'
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5
        with:
          # Only push to the registry on a push to main
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # Only load the docker image on a pull request
          load: ${{ github.event_name == 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: | 
            europe-north1-docker.pkg.dev/knada-gcp/knada-north/${{ env.IMAGE }}:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/${{ env.IMAGE }}:${{ env.TAG }}
