name: Build-and-push-images

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: navikt/knada-git-sync

jobs:
  build-knada-git-sync-image:
    name: Build knada git sync image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set image tag
        run: |
          echo "IMAGE=${IMAGE_NAME}:$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - name: Login Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build dataverk image
        run: docker build -t ${IMAGE} .
      - name: Push dataverk image
        run: docker push ${IMAGE}
