name: Build-and-push-images

on:
  push:
    branches:
      - master

env:
  IMAGE: navikt/knada-git-sync
  AIRFLOW_IAC_REPO: https://api.github.com/repos/navikt/knada-airflow/dispatches

jobs:
  build-knada-git-sync-image:
    name: Build knada git sync image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - name: Login Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build dataverk image
        run: docker build -t ${IMAGE}:${IMAGE_TAG} .
      - name: Push dataverk image
        run: docker push ${IMAGE}:${IMAGE_TAG}
      - name: Notify navikt/knada-airflow of image tag update
        run: |
          curl -X POST "${AIRFLOW_IAC_REPO}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ERIK_PAT }} \
          --data '{"event_type": "update-template-image-tag", "client_payload": { "image": "'"${IMAGE}"'", "tag": "'"${IMAGE_TAG}"'" }}'
