name: Build-and-push-images

on:
  push:
    branches:
      - master

env:
  IMAGE: europe-west1-docker.pkg.dev/knada-gcp/airflow/knada-git-sync

jobs:
  build-knada-git-sync-image:
    name: Build knada git sync image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/193123067890/locations/global/workloadIdentityPools/ci-knada-images/providers/ci-knada-images
          service_account: ci-knada-images@knada-gcp.iam.gserviceaccount.com
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set image tag
        run: echo "IMAGE_TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - name: Build dataverk image
        run: docker build -t ${IMAGE}:${IMAGE_TAG} .
      - name: Push dataverk image
        run: docker push ${IMAGE}:${IMAGE_TAG}
